---
# Create Lambda functions
- name: Archive Lambda source files
  archive:
    path: '{{ lambda_dir }}'
    dest: 'lambda.zip'
    format: 'zip'
- name: Install botocore
  pip:
    name: botocore
- name: Install boto3
  pip:
    name: boto3
- name: Deploy Lambda Function
  lambda:
    name: '{{ lambda_name }}'
    region: '{{ aws_region }}'
    state: present
    zip_file: '{{ zip_file }}'
    runtime: '{{ runtime }}'
    role: '{{ role  }}'
    handler: '{{ handler }}'
    vpc_subnet_ids: '{{ vpc_subnet_ids }}'
    vpc_security_group_ids: '{{ vpc_sec_group_ids }}'
    environment_variables: '{{ env_vars }}'
